export const END_GAME = 'END_GAME';
export const CELL_SELECTION = 'CELL_SELECTION';
export const REGISTER_GAME_WINNING_PEICES = 'REGISTER_GAME_WINNING_PEICES';
export const RESET_GAME = 'RESET_GAME';
export const INC_TIMER = 'INC_TIMER';